#!/bin/bash
# templogger is a script to get and store cpu temperature

# location of system file with the temperature
SYS_TEMP_FILE='/sys/class/thermal/thermal_zone0/temp' 
# log file location 
LOG_DIR="$HOME/.local/share"
LOG_FILE="$LOG_DIR/templogger.txt"

create_log_file () {
    if ! [ -e $LOG_FILE ]; then
        mkdir --parents $LOG_DIR
        touch $LOG_FILE
        HEADER='date time temp'
        echo "$HEADER" >> $LOG_FILE
        echo "Created log file at $LOG_FILE"
    fi
}

log_temp () {
    DATE=$(date +'%Y-%m-%d %H:%M')
    TEMP=$(head -n 1 $SYS_TEMP_FILE | xargs -I{} awk "BEGIN {printf \"%.2f\n\", {}/1000}")
    LOG_STRING="$DATE $TEMP"
    echo "$LOG_STRING" >> $LOG_FILE 
}

print_log () {
    head -n 1 "$LOG_FILE"
    tail -n +2 "$LOG_FILE"
}

case "$1" in
    "log")
        create_log_file
        log_temp;;
    "print")
        print_log;;
esac

