#!/bin/bash
# templog logs cpu temperature to /var/log/temp.log 

# location of system file with the temperature
SYS_TEMP_FILE='/sys/class/thermal/thermal_zone0/temp' 
# log file location 
LOG_DIR="var/log/"
LOG_FILE="$LOG_DIR/temp.log"

print_error_msg () {
    echo 'Not a valid argument. Valid arguments are:'
    printf "\tlog\tWrite temperature to log file\n"
    printf "\tprint\tPrint the last 10 log entries\n" 
    printf "\tplot\tPlot temperatures as of today\n" 
}

create_log_file () {
    if ! [ -e $LOG_FILE ]; then
	echo "Need root permission to create log file"
        sudo touch $LOG_FILE && sudo chmod 777 $LOG_FILE || exit 2 
        echo "Created log file at $LOG_FILE"
    fi
}

log_temp () {
    DATE=$(date +'%Y-%m-%d %H:%M')
    TEMP=$(head -n 1 $SYS_TEMP_FILE | xargs -I{} awk "BEGIN {printf \"%.2f\n\", {}/1000}")
    LOG_STRING="$DATE $TEMP"
    echo "$LOG_STRING" >> $LOG_FILE 
}

print_log () {
    head -n 1 "$LOG_FILE"
    tail -n +2 "$LOG_FILE"
}

plot_log () {
# plot temperatures with gnuplot
TODAY=$(date +"%Y-%m-%d")
DATA=$(awk -v today="${TODAY}" '{if ($1==today) print $2,$3}' $LOG_FILE)
echo "$DATA" > /tmp/plot_data

gnuplot -d -e "set terminal dumb; set xdata time; set timefmt '%M:%S'; \
		set format x '%M:%S'; set title 'Temperatures today (${TODAY})'; \
	set tics scale 0; plot '/tmp/plot_data' using 1:2 with lines notitle"
rm -f /tmp/plot_data
}

case "$1" in
    "log")
        create_log_file
        log_temp
	exit 0;;
    "print")
        print_log
	exit 0;;
    "plot")
        plot_log
	exit 0;;
    *)
        print_error_msg	
	exit 1;;
esac

